#include "keymap.h"


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  // Mostly compatible with ENGRAM; `Q`, `Z` are in the middle columns, middle columns are different
  [ENGRAM] = LAYOUT_ergodox_pretty(
    KC_ESC,         KC_1,           KC_2,           KC_3,           KC_4,             KC_5,           KC_LPRN,                                                KC_RPRN,        KC_6,           KC_7,             KC_8,           KC_9,           KC_0,           KC_PSCR,        //
    KC_TAB,         KC_B,           KC_Y,           KC_O,           KC_U,             KC_Q,           KC_PGUP,                                                KC_UP,          KC_Z,           KC_L,             LT(F_C,KC_D),   LT(F_A,KC_W),   KC_V,           KC_INSERT,      //
    KC_BSPC,        LGUI_T(KC_C),   LALT_T(KC_I),   LCTL_T(KC_E),   LSFT_T(KC_A),     KC_COMMA,                                                                               KC_DOT,         LSFT_T(KC_H),     RCTL_T(KC_T),   LALT_T(KC_S),   RGUI_T(KC_N),   KC_DELETE,      //
    KC_LSFT,        KC_G,           RALT_T(KC_X),   KC_J,           KC_K,             KC_UNDS,        KC_PGDOWN,                                              KC_DOWN,        KC_QUES,        KC_R,             KC_M,           RALT_T(KC_F),   KC_P,           KC_RSFT,        //
    KC_LCTL,        KC_LBRC,        KC_LALT,        KC_COMMA,       LT(MULTI, KC_TAB),                                                                                                        LT(NUM, KC_BSPC), KC_DOT,         KC_RALT,        KC_RBRC,        KC_RCTL,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      KC_HOME,        KC_END,               KC_LEFT,          KC_RIGHT,                                                                                                         //
                                                                                                                      KC_LGUI,              KC_APP,                                                                                                                             //
                                                                                      KC_SPACE,       TD(TD_RAISE),   LT(MOUSE, KC_ESC),    LT(FUNC, KC_DEL), KC_ENTER,       OSL(LOWER)                                                                                        //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // Mostly compatible with QWERTY; `-`, `+`, `=` are on LOWER layer; `_` is at the bottom
  [QWERTY] = LAYOUT_ergodox_pretty(
    KC_ESC,         KC_1,           KC_2,           KC_3,           KC_4,             KC_5,           KC_LPRN,                                                KC_RPRN,        KC_6,           KC_7,             KC_8,           KC_9,           KC_0,           KC_PSCR,        //
    KC_TAB,         KC_Q,           KC_W,           KC_E,           KC_R,             KC_T,           KC_PGUP,                                                KC_UP,          KC_Y,           KC_U,             LT(F_C,KC_I),   LT(F_A,KC_O),   KC_P,           KC_INSERT,      //
    KC_BSPC,        LGUI_T(KC_A),   LALT_T(KC_S),   LCTL_T(KC_D),   LSFT_T(KC_F),     KC_G,                                                                                   KC_H,           LSFT_T(KC_J),     RCTL_T(KC_K),   LALT_T(KC_L),   RGUI_T(KC_SCLN),KC_DELETE,      //
    KC_LSFT,        KC_Z,           RALT_T(KC_X),   KC_C,           KC_V,             KC_B,           KC_PGDOWN,                                              KC_DOWN,        KC_N,           KC_M,             KC_COMMA,       RALT_T(KC_DOT), KC_SLASH,       KC_RSFT,        //
    KC_LCTL,        KC_LBRC,        KC_LALT,        KC_UNDS,        LT(MULTI, KC_TAB),                                                                                                        LT(NUM, KC_BSPC), KC_COMMA,       KC_RALT,        KC_RBRC,        KC_RCTL,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      KC_HOME,        KC_END,               KC_LEFT,          KC_RIGHT,                                                                                                         //
                                                                                                                      KC_LGUI,              KC_APP,                                                                                                                             //
                                                                                      KC_SPACE,       TD(TD_RAISE),   LT(MOUSE, KC_ESC),    LT(FUNC, KC_DEL), KC_ENTER,       OSL(LOWER)                                                                                        //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // Russian phonetic Engram layout: Switched on left keyboard half: Win+Space (activated programmatically)
  //                б               ы               о               у                 ч                                                                                       з               л                 д               ш              в
  //                ц               и               е               а                 ,                                                                                       .               х                 т               с              н
  //                г               ж               й               к                 _                                                                                       ?               р                 м               ф              п
  [RPE] = LAYOUT_ergodox_pretty(
    _______,        _______,        _______,        _______,        _______,          _______,        _______,                                                _______,        _______,        _______,          _______,        _______,        _______,        _______,        //
    _______,        KC_COMMA,       KC_S,           KC_J,           KC_E,             KC_X,           _______,                                                _______,        KC_P,           KC_K,             LT(F_C,KC_L),   LT(F_A,KC_I),   KC_D,           _______,        //
    _______,        LGUI_T(KC_W),   LALT_T(KC_B),   LCTL_T(KC_T),   LSFT_T(KC_F),     KC_QUES,                                                                                KC_SLASH,       RSFT_T(KC_LBRC),  RCTL_T(KC_N),   LALT_T(KC_C),   RGUI_T(KC_Y),   _______,        //
    _______,        KC_U,           RALT_T(KC_SCLN),KC_Q,           KC_R,             KC_UNDS,        _______,                                                _______,        KC_AMPR,        KC_H,             KC_V,           RALT_T(KC_A),   KC_G,           _______,        //
    _______,        _______,        _______,        KC_UNDS,        _______,                                                                                                                  _______,          KC_COMMA,       _______,        _______,        _______,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      _______,        _______,              _______,          _______,                                                                                                          //
                                                                                                                      _______,              _______,                                                                                                                            //
                                                                                      _______,        _______,        _______,              _______,          _______,        OSL(R_LOWER)                                                                                      //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // Symbols layer, activated when LOWER is tapped or held
  [LOWER] = LAYOUT_ergodox_pretty(
    _______,        _______,        _______,        _______,        _______,          _______,        _______,                                                _______,        _______,        _______,          _______,        _______,        _______,        _______,        //
    _______,        KC_EXLM,        KC_LT,          KC_GT,          KC_AMPR,          KC_CIRC,        _______,                                                _______,        KC_TILDE,       KC_AT,            KC_LBRACKET,    KC_RBRACKET,    KC_GRAVE,       _______,        //
    _______,        KC_MINUS,       KC_LPRN,        KC_RPRN,        KC_EQUAL,         KC_0,                                                                                   KC_2,           KC_SCOLON,        KC_LCBR,        KC_RCBR,        KC_DQUO,        _______,        //
    _______,        KC_PLUS,        KC_ASTERISK,    KC_SLASH,       KC_PIPE,          KC_1,           _______,                                                _______,        KC_3,           KC_COLON,         KC_DOLLAR,      KC_PERC,        KC_QUOTE,       _______,        //
    _______,        _______,        _______,        _______,        KC_HASH,                                                                                                                  KC_TILDE,         _______,        _______,        _______,        _______,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      _______,        _______,              _______,          _______,                                                                                                          //
                                                                                                                      _______,              _______,                                                                                                                            //
                                                                                      _______,        KC_UNDS,        C(KC_SLASH),          KC_CIRC,          KC_BSLASH,      KC_COMMA                                                                                          //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // LOWER layer, when activated from RPE (russian layout): same as LOWER, except characters that cannot be typed + extra russian characters
  [R_LOWER] = LAYOUT_ergodox_pretty(
    _______,        _______,        _______,        _______,        _______,          _______,        _______,                                                _______,        _______,        _______,          _______,        _______,        _______,        _______,        //
    _______,        KC_EXLM,        KC_QUOT, /*э*/  KC_GRV,/*ё*/    KC_DOT,  /*ю*/    KC_CIRC,        _______,                                                _______,        KC_TILDE,       XXXXXXX,          XXXXXXX,        KC_O,    /*щ*/  XXXXXXX,        _______,        //
    _______,        KC_MINUS,       KC_LPRN,        KC_RPRN,        KC_EQUAL,         KC_0,                                                                                   KC_2,           KC_DOLLAR,/*;*/   KC_M,    /*ь*/  KC_RBRC, /*ъ*/  KC_AT,   /*"*/  _______,        //
    _______,        KC_PLUS,        KC_ASTERISK,    KC_PIPE,/*/*/   KC_Z,    /*я*/    KC_1,           _______,                                                _______,        KC_3,           KC_CIRC,  /*:*/   KC_RBRC, /*ъ*/  KC_PERC,        XXXXXXX,        _______,        //
    _______,        _______,        _______,        _______,        KC_HASH, /*№*/                                                                                                            XXXXXXX,          _______,        _______,        _______,        _______,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      _______,        _______,              _______,          _______,                                                                                                          //
                                                                                                                      _______,              _______,                                                                                                                            //
                                                                                      KC_SPACE,       KC_UNDS,        _______,              _______,          KC_BSLASH,      KC_QUES /*,*/                                                                                     //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // Historically, multimedia layer, now only programming macros
  [MULTI] = LAYOUT_ergodox_pretty(
    _______,        _______,        _______,        _______,        _______,          _______,        _______,                                                _______,        _______,        _______,          _______,        _______,        _______,         _______,       //
    _______,        LCTL(KC_B),     LCTL(KC_Y),     LCTL(KC_O),     LCTL(KC_U),       LCTL(KC_Q),     _______,                                                _______,        KC_PQUEUE,      KC_LINKED,        KC_ARRAY,       KC_LIST,        KC_DEQUEUE,      _______,       //
    _______,        LCTL(KC_C),     LCTL(KC_I),     LCTL(KC_E),     LCTL(KC_A),       C(KC_COMM),                                                                             KC_COMP,        KC_LT,            KC_COMMA,       KC_SPACE,       KC_GT,           _______,       //
    _______,        LCTL(KC_G),     LCTL(KC_X),     LCTL(KC_J),     LCTL(KC_K),       C(KC_SCLN),     _______,                                                _______,        KC_ENTRY,       KC_TREE,          KC_HASH_,       KC_MAP,         KC_SET,          _______,       //
    _______,        _______,        _______,        _______,        XXXXXXX,                                                                                                                  KC_CHAR,          _______,        _______,        _______,         _______,       //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      _______,        _______,              _______,          _______,                                                                                                          //
                                                                                                                      _______,              _______,                                                                                                                            //
                                                                                      RCS(KC_C),      RCS(KC_V),      TG(ENGRAM),           KC_NEW,           KC_INT,         KC_STR                                                                                            //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // Historically, multimedia layer, now only programming macros (invoked from QWERTY)
  // TODO: then, need QMOUSE, QFUNC? easier to do it programmatically?
  [QMULTI] = LAYOUT_ergodox_pretty(
    _______,        _______,        _______,        _______,        _______,          _______,        _______,                                                _______,        _______,        _______,          _______,        _______,        _______,         _______,       //
    _______,        LCTL(KC_Q),     LCTL(KC_W),     LCTL(KC_E),     LCTL(KC_R),       LCTL(KC_T),     _______,                                                _______,        KC_PQUEUE,      KC_LINKED,        KC_ARRAY,       KC_LIST,        KC_DEQUEUE,      _______,       //
    _______,        LCTL(KC_A),     LCTL(KC_S),     LCTL(KC_D),     LCTL(KC_F),       LCTL(KC_G),                                                                             KC_COMP,        KC_LT,            KC_COMMA,       KC_SPACE,       KC_GT,           _______,       //
    _______,        LCTL(KC_Z),     LCTL(KC_X),     LCTL(KC_C),     LCTL(KC_V),       LCTL(KC_B),     _______,                                                _______,        KC_ENTRY,       KC_TREE,          KC_HASH_,       KC_MAP,         KC_SET,          _______,       //
    _______,        _______,        _______,        _______,        XXXXXXX,                                                                                                                  KC_CHAR,          _______,        _______,        _______,         _______,       //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      _______,        _______,              _______,          _______,                                                                                                          //
                                                                                                                      _______,              _______,                                                                                                                            //
                                                                                      RCS(KC_C),      RCS(KC_V),      TG(QWERTY),           KC_NEW,           KC_INT,         KC_STR                                                                                            //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // MOUSE (+media)
  [MOUSE] = LAYOUT_ergodox_pretty(
    _______,        _______,        _______,        _______,        _______,          _______,        _______,                                                _______,        _______,        _______,          _______,        _______,        _______,         _______,       //
    _______,        LALT(KC_B),     LALT(KC_Y),     LALT(KC_O),     LALT(KC_U),       LALT(KC_Q),     _______,                                                _______,        KC_MEDIA_STOP,  KC_MPRV,          KC_VOLD,        KC_VOLU,        KC_MNXT,         _______,       //
    _______,        LALT(KC_C),     LALT(KC_I),     LALT(KC_E),     LALT(KC_A),       LALT(KC_COMM),                                                                          KC_MPLY,        KC_MS_LEFT,       KC_MS_DOWN,     KC_MS_UP,       KC_MS_RIGHT,     _______,       //
    _______,        LALT(KC_G),     LALT(KC_X),     LALT(KC_J),     LALT(KC_K),       LALT(KC_SCLN),  _______,                                                _______,        KC_MUTE,        KC_WH_L,          KC_WH_D,        KC_WH_U,        KC_WH_R,         _______,       //
    _______,        _______,        _______,        _______,        XXXXXXX,                                                                                                                  KC_BTN2,          _______,        _______,        _______,         _______,       //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      _______,        _______,              _______,          _______,                                                                                                          //
                                                                                                                      _______,              _______,                                                                                                                            //
                                                                                      XXXXXXX,        XXXXXXX,        XXXXXXX,              KC_MUTE,          KC_BTN1,        KC_BTN3                                                                                           //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
 ),


  [FUNC] = LAYOUT_ergodox_pretty(
    XXXXXXX,        KC_F1,          KC_F2,          KC_F3,          KC_F4,            KC_F5,          XXXXXXX,                                                XXXXXXX,        KC_F6,          KC_F7,            KC_F8,          KC_F9,          KC_F10,         XXXXXXX,        //
    XXXXXXX,        KC_F12,         KC_F7,          KC_F8,          KC_F9,            KC_PSCR,        XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        KC_F11,         KC_F4,          KC_F5,          KC_F6,            KC_SLCK,                                                                                XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        KC_F10,         KC_F1,          KC_F2,          KC_F3,            KC_PAUSE,       XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX ,       LALT(KC_TAB),                                                                                                             XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      XXXXXXX,        XXXXXXX,              XXXXXXX,          XXXXXXX,                                                                                                          //
                                                                                                                      XXXXXXX,              XXXXXXX,                                                                                                                            //
                                                                                      KC_INSERT,      KC_APPLICATION, LALT(KC_ESC),         XXXXXXX,          KC_TURBO,       XXXXXXX                                                                                           //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // TG(NUM) does not work
  [NUM] = LAYOUT_ergodox_pretty(
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        KC_MINUS,       KC_7,           KC_8,           KC_9,             KC_SLASH,       XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        KC_PLUS,        KC_4,           KC_5,           KC_6,             KC_EQUAL,                                                                               XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        KC_DOT,         KC_1,           KC_2,           KC_3,             KC_ASTR,        XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX ,       KC_DOT,                                                                                                                   XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      XXXXXXX,        XXXXXXX,              XXXXXXX,          XXXXXXX,                                                                                                          //
                                                                                                                      XXXXXXX,              XXXXXXX,                                                                                                                            //
                                                                                      KC_0,           KC_SPACE,       XXXXXXX,              XXXXXXX,          XXXXXXX,        XXXXXXX                                                                                            //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // Basic navigation layer, momentarily activated by RAISE hold; locked after RAISE long tap
  [NAV2] = LAYOUT_ergodox_pretty(
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        A(KC_LEFT),     A(KC_DOWN),     A(KC_UP),       A(KC_RIGHT),      C(KC_A),        XXXXXXX,                                                XXXXXXX,        C(KC_W),        A(KC_HOME),       A(KC_PGDOWN),   A(KC_PGUP),     A(KC_END),      XXXXXXX,        //
    XXXXXXX,        C(KC_LEFT),     C(KC_DOWN),     C(KC_UP),       C(KC_RIGHT),      C(KC_C),                                                                                C(KC_V),        KC_LEFT,          KC_DOWN,        KC_UP,          KC_RIGHT,       XXXXXXX,        //
    XXXXXXX,        C(KC_HOME),     C(KC_PGDOWN),   C(KC_PGUP),     C(KC_END),        C(KC_Z),        XXXXXXX,                                                XXXXXXX,        C(KC_X),        KC_HOME,          KC_PGDOWN,      KC_PGUP,        KC_END,         XXXXXXX,        //
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX ,       KC_TAB,                                                                                                                   KC_BSPC,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      XXXXXXX,        XXXXXXX,              XXXXXXX,          XXXXXXX,                                                                                                          //
                                                                                                                      XXXXXXX,              XXXXXXX,                                                                                                                            //
                                                                                      C(KC_ENT),      KC_ALT_ERASE,   KC_ESC,               C(KC_DEL),        KC_ENT,         TT(S_NAV2)                                                                                        //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  // Basic navigation layer, momentarily activated by RAISE hold; locked after RAISE long tap
  [S_NAV2] = LAYOUT_ergodox_pretty(
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        LSA(KC_LEFT),   LSA(KC_DOWN),   LSA(KC_UP),     LSA(KC_RIGHT),    RCS(KC_A),      XXXXXXX,                                                XXXXXXX,        RCS(KC_W),      LSA(KC_HOME),     LSA(KC_PGDOWN), LSA(KC_PGUP),   A(KC_END),      XXXXXXX,        //
    XXXXXXX,        RCS(KC_LEFT),   RCS(KC_DOWN),   RCS(KC_UP),     RCS(KC_RIGHT),    RCS(KC_C),                                                                              RCS(KC_V),      S(KC_LEFT),       S(KC_DOWN),     S(KC_UP),       S(KC_RIGHT),    XXXXXXX,        //
    XXXXXXX,        RCS(KC_HOME),   RCS(KC_PGDOWN), RCS(KC_PGUP),   RCS(KC_END),      RCS(KC_Z),      XXXXXXX,                                                XXXXXXX,        RCS(KC_X),      S(KC_HOME),       S(KC_PGDOWN),   S(KC_PGUP),     S(KC_END),      XXXXXXX,        //
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX ,       KC_TAB,                                                                                                                   RCS(KC_BSPC),     XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      XXXXXXX,        XXXXXXX,              XXXXXXX,          XXXXXXX,                                                                                                          //
                                                                                                                      XXXXXXX,              XXXXXXX,                                                                                                                            //
                                                                                      C(KC_ENT),      KC_ALT_ERASE,   KC_ESC,               XXXXXXX,          KC_ENT,         XXXXXXX                                                                                           //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  [F_A] = LAYOUT_ergodox_pretty(
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        A(KC_F12),      A(KC_F7),       A(KC_F8),       A(KC_F9),         A(KC_PSCR),     XXXXXXX,                                                XXXXXXX,        XXXXXXX,        KC_LSFT,          KC_LCTL,        KC_LALT,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        A(KC_F11),      A(KC_F4),       A(KC_F5),       A(KC_F6),         A(KC_SLCK),                                                                             XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        A(KC_F10),      A(KC_F1),       A(KC_F2),       A(KC_F3),         A(KC_PAUSE),    XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX ,       XXXXXXX,                                                                                                                  XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      XXXXXXX,        XXXXXXX,              XXXXXXX,          XXXXXXX,                                                                                                          //
                                                                                                                      XXXXXXX,              XXXXXXX,                                                                                                                            //
                                                                                      A(KC_INS),      A(KC_APP),      XXXXXXX,              XXXXXXX,          XXXXXXX,       XXXXXXX                                                                                            //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),

  [F_C] = LAYOUT_ergodox_pretty(
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        C(KC_F12),      C(KC_F7),       C(KC_F8),       C(KC_F9),         C(KC_PSCR),     XXXXXXX,                                                XXXXXXX,        XXXXXXX,        KC_LSFT,          KC_LCTL,        KC_LALT,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        C(KC_F11),      C(KC_F4),       C(KC_F5),       C(KC_F6),         C(KC_SLCK),                                                                             XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        C(KC_F10),      C(KC_F1),       C(KC_F2),       C(KC_F3),         C(KC_PAUSE),    XXXXXXX,                                                XXXXXXX,        XXXXXXX,        XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
    XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX ,       XXXXXXX,                                                                                                                  XXXXXXX,          XXXXXXX,        XXXXXXX,        XXXXXXX,        XXXXXXX,        //
 // ---------------------------------------------------------------|-----------------|-------------------------------------------------|   |-------------------------------------------------|-----------------|----------------------------------------------------------------//
                                                                                                      XXXXXXX,        XXXXXXX,              XXXXXXX,          XXXXXXX,                                                                                                          //
                                                                                                                      XXXXXXX,              XXXXXXX,                                                                                                                            //
                                                                                      C(KC_INS),      C(KC_APP),      XXXXXXX,              XXXXXXX,          XXXXXXX,       XXXXXXX                                                                                            //
 //                                                                                  |-------------------------------------------------|   |---------------------------------------------|                                                                                      //
  ),
};
